# Generated by Django 4.2.13 on 2024-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Kirim', 'Kirim'), ('Chiqim', 'Chiqim')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
